# Generated by Django 2.1.2 on 2018-10-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
