# Generated by Django 2.1.2 on 2018-10-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_faculty_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_subTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profil_images'),
        ),
    ]
