# Generated by Django 2.1.2 on 2018-10-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_auto_20181018_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certi_img', models.ImageField(blank=True, null=True, upload_to='certi_images')),
                ('certi_title', models.CharField(max_length=50)),
            ],
        ),
    ]
