# Generated by Django 2.1.2 on 2018-10-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
