# Generated by Django 2.1.2 on 2018-10-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sponsor', models.CharField(max_length=100)),
                ('Principal_Investigator', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
