# Generated by Django 2.1.2 on 2018-10-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_auto_20181019_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_status',
            field=models.CharField(blank=True, choices=[('NV', 'Not yet verified'), ('AV', 'Application verified'), ('CC', 'Course completed')], default='NV', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='fee_status',
            field=models.CharField(blank=True, choices=[('NP', 'Not paid'), ('PP', 'Partially Paid'), ('FP', 'Fully Paid')], default='NP', max_length=2, null=True),
        ),
    ]
